//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iw
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bus()
        {
            this.busDriverPassengers = new HashSet<busDriverPassenger>();
        }
    
        public int id { get; set; }
        public string plaka { get; set; }
        public string model { get; set; }
        public string picturePath { get; set; }
        public string capacity { get; set; }
        public string engelli { get; set; }
        public string klima { get; set; }
        public System.Data.Entity.Spatial.DbGeography currentLocation { get; set; }
        public string busLineName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<busDriverPassenger> busDriverPassengers { get; set; }
    }
}
