//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iw
{
    using System;
    using System.Collections.Generic;
    
    public partial class busDriverPassenger
    {
        public int busID { get; set; }
        public int peopleID { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual people111 people111 { get; set; }
        public virtual person person { get; set; }
    }
}
