//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iw
{
    using System;
    using System.Collections.Generic;
    
    public partial class busStop
    {
        public int id { get; set; }
        public string name { get; set; }
        public string picturePath { get; set; }
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
        public string chairTF { get; set; }
        public string bookTF { get; set; }
    }
}
