//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iw
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.busDriverPassengers = new HashSet<busDriverPassenger>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string department { get; set; }
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
        public System.Data.Entity.Spatial.DbGeography pathToSchool { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<busDriverPassenger> busDriverPassengers { get; set; }
    }
}
